services:
  - type: web
    name: flask-chat
    env: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 main:app