"""youtube tracking table

Revision ID: 1154c2cf84f7
Revises: 6a961d6cc9cd
Create Date: 2026-05-26 16:06:03.438379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1154c2cf84f7'
down_revision = '6a961d6cc9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('strip_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_tracking')
    # ### end Alembic commands ###
