"""recreate youtube tracking table

Revision ID: 1de22bf6b6f0
Revises: a2e869d17e44
Create Date: 2026-05-30 16:37:10.879162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de22bf6b6f0'
down_revision = 'a2e869d17e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('strip_name', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_tracking')
    # ### end Alembic commands ###
