"""cascade delete fix

Revision ID: 6a961d6cc9cd
Revises: 31f409792331
Create Date: 2026-05-25 17:54:17.706588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a961d6cc9cd'
down_revision = '31f409792331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_visibility', schema=None) as batch_op:
        batch_op.alter_column('hidden_for_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('chat_message_visibility_hidden_for_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['hidden_for_user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message_visibility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_message_visibility_hidden_for_user_id_fkey'), 'users', ['hidden_for_user_id'], ['id'])
        batch_op.alter_column('hidden_for_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
