"""youtube automation

Revision ID: 8f40ebce0584
Revises: 1785e6286b81
Create Date: 2026-05-29 10:52:46.084372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f40ebce0584'
down_revision = '1785e6286b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_scanned_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    with op.batch_alter_table('youtube_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scan_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_channel', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_scan_at')

    op.drop_table('youtube_scanned_video')
    # ### end Alembic commands ###
