"""commercial tables

Revision ID: 9101f22e8243
Revises: 1de22bf6b6f0
Create Date: 2026-06-03 12:37:07.321458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9101f22e8243'
down_revision = '1de22bf6b6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=False),
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_name', sa.String(length=255), nullable=False),
    sa.Column('ad_type', sa.String(length=100), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_acquisition', sa.String(length=255), nullable=True),
    sa.Column('sample_images', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commercial_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_name', sa.String(length=255), nullable=True),
    sa.Column('ad_type', sa.String(length=100), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('views', sa.String(length=100), nullable=True),
    sa.Column('publish_date', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_acquisition', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commercial_result')
    op.drop_table('commercial_client')
    op.drop_table('commercial_channel')
    # ### end Alembic commands ###
