"""create youtube tracking

Revision ID: a2e869d17e44
Revises: ead69115ca4e
Create Date: 2026-05-30 14:19:29.855283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2e869d17e44'
down_revision = 'ead69115ca4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('published_date', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['youtube_channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_url')
    )
    op.drop_table('youtube_scanned_video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_scanned_video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('scanned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_scanned_video_pkey')),
    sa.UniqueConstraint('video_id', name=op.f('youtube_scanned_video_video_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('youtube_tracking')
    # ### end Alembic commands ###
