"""chat upgrade

Revision ID: b2bd182f3fd4
Revises: 102455b79299
Create Date: 2026-05-20 09:49:02.932271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bd182f3fd4'
down_revision = '102455b79299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('deleted')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_name')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
