"""add channel id

Revision ID: ead69115ca4e
Revises: 8f40ebce0584
Create Date: 2026-05-30 14:12:04.915196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ead69115ca4e'
down_revision = '8f40ebce0584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_scanned_video')
    with op.batch_alter_table('youtube_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('video_title', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('published_date', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['video_url'])
        batch_op.create_foreign_key(None, 'youtube_channel', ['channel_id'], ['id'])
        batch_op.drop_column('channel_name')
        batch_op.drop_column('link')
        batch_op.drop_column('strip_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_tracking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strip_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('channel_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('published_date')
        batch_op.drop_column('video_url')
        batch_op.drop_column('video_title')
        batch_op.drop_column('channel_id')

    op.create_table('youtube_scanned_video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('scanned_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_scanned_video_pkey')),
    sa.UniqueConstraint('video_id', name=op.f('youtube_scanned_video_video_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
